shared_settings: &shared_settings
  project_name: ""
  watermarkchurchURL: "https://virtserver.swaggerhub.com/watermark/jtj/0"
  sendgrid_username: "shaik.rabbit"
  sendgrid_password: "Rabbit*123"
  sendgrid_domain: "https://jtj.herokuapp.com"

  
development: &non_production_settings
  <<: *shared_settings
  domain: localhost:3000

test:
  <<: *non_production_settings
  <<: *shared_settings

staging:
  <<: *non_production_settings
  <<: *shared_settings

production:
  disqus_short_name: watermark
  domain: jtj.herokuapp.com
  <<: *shared_settings